# Generated by Django 3.2.14 on 2022-08-09 00:37

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='imgs_org/default.png', null=True, upload_to=places.models.upload_img),
        ),
    ]
