# Generated by Django 3.2.14 on 2022-08-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_comentario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
