# Generated by Django 3.2.14 on 2022-08-11 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_rename_is_activate_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
